---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: kubewatch
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kubewatch
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: robusta
        namespace: kube-system
      interval: 5m
  releaseName: kubewatch
  values:
    rbac:
      create: true
      customRoles:
        - apiGroups: ["kustomize.toolkit.fluxcd.io"]
          resources: ["kustomizations"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["helm.toolkit.fluxcd.io"]
          resources: ["helmreleases"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["source.toolkit.fluxcd.io"]
          resources: ["gitrepositories", "helmrepositories", "helmcharts"]
          verbs: ["get", "list", "watch"]
    resourcesToWatch:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
      job: false
      node: false
      clusterrole: true
      clusterrolebinding: true
      serviceaccount: true
      persistentvolume: false
      namespace: false
      secret: false
      configmap: false
      ingress: false
      coreevent: false
      event: true
    customresources:
      - group: kustomize.toolkit.fluxcd.io
        version: v1
        resource: kustomizations
      - group: helm.toolkit.fluxcd.io
        version: v2
        resource: helmreleases
      - group: source.toolkit.fluxcd.io
        version: v1
        resource: gitrepositories
      - group: source.toolkit.fluxcd.io
        version: v1
        resource: helmrepositories
      - group: source.toolkit.fluxcd.io
        version: v1
        resource: helmcharts
    slackwebhookurl:
      enabled: true
      channel: "#kubewatch-homelab"
      username: "kubewatch"
      emoji: ":robot_face:"
    extraEnvVars:
      - name: KW_SLACK_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: kubewatch
            key: webhook_url
