apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: measurement

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus-config/prometheus.yaml

resources:
  - namespace.yaml
  - serviceaccount.yaml

  - secrets.yaml

  - prometheus.yaml
  - grafana.yaml
