global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "hass"
    metrics_path: /api/prometheus

    authorization:
      credentials_file: "/secrets/hass_prometheus_token"

    static_configs:
      - targets: ["hass.homepi.svc.cluster.local:8123"]

  # - job_name: "node-exporter"
  #   scrape_interval: 15s
  #   scrape_timeout: 10s

  #   kubernetes_sd_configs:
  #     - role: endpoints
  #       namespaces:
  #         names:
  #           - kube-system

  #   relabel_configs:
  #     # Only keep targets that are from the prometheus-node-exporter service
  #     - source_labels: [__meta_kubernetes_service_name]
  #       action: keep
  #       regex: prometheus-node-exporter

  #     # Only keep endpoints that are on the metrics port
  #     - source_labels: [__meta_kubernetes_endpoint_port_name]
  #       action: keep
  #       regex: metrics

  #     # Add node name as a label from the pod's node name
  #     - source_labels: [__meta_kubernetes_pod_node_name]
  #       action: replace
  #       target_label: node
  #       regex: (.*)
  #       replacement: ${1}

  #     # Add instance label using the node name
  #     - source_labels: [__meta_kubernetes_pod_node_name]
  #       action: replace
  #       target_label: instance
  #       regex: (.*)
  #       replacement: ${1}
