apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metropolitan-real

resources:
  - namespace.yaml
  - serviceaccount.yaml

  - secrets.yaml

  - postgres.yaml
  - postgres17.yaml
  - app.yaml
