apiVersion: v1
kind: PersistentVolume
metadata:
  name: metropolitan-real-postgres
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/local/kube-volumes/metropolitan-real-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - db
