---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/local/kube-volumes/jackett-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: edge
              operator: In
              values:
                - homenuc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-pvc
  namespace: pirate
  labels:
    app: jackett
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: jackett-config
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
