---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: pirate
spec:
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
  selector:
    app: jackett
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  namespace: pirate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - jackett.kislan.sk
      secretName: jackett-kislan-sk
  rules:
    - host: jackett.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: 9117
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jackett
  namespace: pirate
spec:
  serviceName: jackett
  selector:
    matchLabels:
      app: jackett
  replicas: 1
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: linuxserver/jackett:0.24.72
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Europe/Bratislava
      volumes:
        - name: config
          hostPath:
            path: /var/local/kube-volumes/jackett-config
            type: DirectoryOrCreate
      tolerations:
        - key: edge
          operator: Equal
          value: "homenuc"
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
