apiVersion: batch/v1
kind: CronJob
metadata:
  name: plextraktsync
  namespace: pirate
spec:
  schedule: "5 9-23,0-1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: config
              hostPath:
                path: /var/local/kube-volumes/plextraktsync-config
                type: DirectoryOrCreate
          containers:
            - name: plextraktsync
              image: ghcr.io/taxel/plextraktsync:0.34.1
              imagePullPolicy: Always
              args:
                - sync
              volumeMounts:
                - name: config
                  mountPath: /app/config
              env:
                - name: PUID
                  value: "1000"
                - name: PGID
                  value: "1000"
                - name: TZ
                  value: Europe/Bratislava
                - name: PLEX_USERNAME
                  value: kislan0
                - name: TRAKT_USERNAME
                  value: pinker
                - name: PLEX_SERVER
                  value: homenuc
          tolerations:
            - key: edge
              operator: Equal
              value: homenuc
              effect: NoExecute
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: edge
                        operator: In
                        values:
                          - homenuc
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: plextraktsync
#   namespace: pirate
# spec:
#   serviceName: plextraktsync
#   selector:
#     matchLabels:
#       app: plextraktsync
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: plextraktsync
#     spec:
#       volumes:
#         - name: config
#           hostPath:
#             path: /var/local/kube-volumes/plex-config
#             type: DirectoryOrCreate
#         - name: servers
#           configMap:
#             name: plextraktsync-servers
#             defaultMode: 0777
#       containers:
#         - name: plextraktsync
#           image: ghcr.io/taxel/plextraktsync:0.33.0
#           imagePullPolicy: Always
#           volumeMounts:
#             - name: config
#               mountPath: /app/config
#           env:
#             - name: PUID
#               value: "1000"
#             - name: PGID
#               value: "1000"
#             - name: TZ
#               value: Europe/Bratislava
#       tolerations:
#         - key: edge
#           operator: Equal
#           value: homenuc
#           effect: NoExecute
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#               - matchExpressions:
#                   - key: edge
#                     operator: In
#                     values:
#                       - homenuc
