---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: pirate
spec:
  ports:
    - port: 32400
      targetPort: 32400
      protocol: TCP
  selector:
    app: plex
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: pirate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - plex.kislan.sk
      secretName: plex-kislan-sk
  rules:
    - host: plex.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  labels:
    name: plex
spec:
  serviceName: plex
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - name: config
          hostPath:
            path: /var/local/kube-volumes/plex-config
            type: DirectoryOrCreate
        - name: transcode
          hostPath:
            path: /root/storage/pirate/plex/transcode
            type: DirectoryOrCreate
        - name: movies
          hostPath:
            path: /root/storage/pirate/library/movies
            type: DirectoryOrCreate
        - name: tvshows
          hostPath:
            path: /root/storage/pirate/library/tvshows
            type: DirectoryOrCreate
      containers:
        - name: plex
          image: plexinc/pms-docker:1.40.2.8395-c67dce28e
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 5
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /transcode
              name: transcode
            - mountPath: /data/movies
              name: movies
            - mountPath: /data/tvshows
              name: tvshows
          env:
            - name: PLEX_UID
              value: "0"
            - name: PLEX_GID
              value: "0"
            - name: TZ
              value: "Europe/Bratislava"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex
                  key: claim
      tolerations:
        - key: edge
          operator: Equal
          value: "homenuc"
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
