---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: pirate
spec:
  ports:
    - port: 9696
      targetPort: 9696
      protocol: TCP
  selector:
    app: prowlarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: pirate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - prowlarr.kislan.sk
      secretName: prowlarr-kislan-sk
  rules:
    - host: prowlarr.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: pirate
spec:
  serviceName: prowlarr
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:2.1.5
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Europe/Bratislava
      volumes:
        - name: config
          hostPath:
            path: /var/local/kube-volumes/prowlarr-config
            type: DirectoryOrCreate
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
