---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: pirate
spec:
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
  selector:
    app: radarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: pirate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - movies.kislan.sk
      secretName: radarr-movies-kislan-sk
  rules:
    - host: movies.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: pirate
spec:
  serviceName: radarr
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:5.18.4
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: downloads2
              mountPath: /downloads2
            - name: library
              mountPath: /movies
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Europe/Bratislava
      volumes:
        - name: config
          hostPath:
            path: /var/local/kube-volumes/radarr3-config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /root/storage/pirate/downloads
            type: DirectoryOrCreate
        - name: downloads2
          hostPath:
            path: /root/storage2/pirate/downloads
            type: DirectoryOrCreate
        - name: library
          hostPath:
            path: /root/storage/pirate/library/movies
            type: DirectoryOrCreate
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
