apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mullvadvpn
  namespace: pirate
spec:
  encryptedData:
    account_id: AgCLZLAI5OMgQJ11MX1RX/a70qVUwaXyvKwgDvUUUPlurRTdzXy8P4EWt5yKFHlLKzFg/HDgbIu6XY4n20d4w0gnBchYiCzHoVvDL8ooizhTqzvyAJVjEPzUanAfk1UGdz8Gw0PwXiV76DWWGVDNQ+MtKGk5mqBOMymzLDuxnEzB3BNWs4FZAFcswwI8kzl0H9Zd7jhX+crPURhM+HpYdgLEEYm0zbw6/V+fCgrcJ0oeXvlMvXrNnWq/x8MaPpK3KzlTGOWBtuDtL6Qj2WGsE2fmE7zuBR2/vKCUYfzEnCMj1rPF/nVK5o5AzfBifI3oy9Rfu3s39kkcSymF3VdDYwNySczYVe4LcbpGxhJkE9q0yIA9zYvYVbnjZU0WvZRUHSDiJ6O7hd+rOCFwB5r2N7QFdMAAioXl4Ea/LmMV5pkz3/afNmOu3Rnk6ZS1/7T7aR7i6LEr3wu9woRobpzA6xkOxND43mZzw+uMPiknZpR+n5pfGryN85zbiiZftuTex+7Ew7o2I5mOMDygkmZtqxjjBsBWZpwX+M2TksITK0ImIKsdG6tR/93/J/0w8Or9r11hmgtr5aCITTTsFNainI5ybFLKAvEYTCI7rN19qUipqa4k/cQjq7FgLBuDUNlJzr7/xpnz83VIA0RNXTpqW9/Y5YVqe9FfPhoWqM+096+ft9dpL+xVioI52N7CiclyTOfi/yP5ZW4jEWY3zSaZ4mRe
  template:
    metadata:
      creationTimestamp: null
      name: mullvadvpn
      namespace: pirate
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission
  namespace: pirate
spec:
  encryptedData:
    password: AgBnaFZiWXlRnMEjdjY7b2p6k53AFKopgaZpcLVf2nuUjy4Hjzgwhm3+e9dmIqRXwlyXW9G/UxptVh//MQ2dxKsgEnF1xEWrjChqyE11ykepZGsBNhpzOFN9DVjlCnBrhE2UVSd/g/pUFGLcPD/Dq7H7MLC1FE0qT6xGl8V/LYJps9lKUPom3PuZS04J5z3oX8fk0rq2pllopJPNqEjORvtDhsD2OO2XD1nLfBId2imP62D3qGw7h0eoUigPvF4kvwj/zwRsE5NOfOl9onbK9YPYfWEGpBXco3SLoWwb/qAAAgnmdF3/RfZucvzPvSEAWGSnzWp/1vTB5k+EGtf3zB5cKhNh3vAARGbbYHPMEJ1mEFKfKyIqU8mNR9ylzp1affwBTyt34UGrXApbszCyZFKOh8I5hGgzdsRwQgnRZMZKyKaV0qaR+oTfV0yBFWQs3D+8vDDMnroeRC6DqMkcvUdu6hj2RLLqb1WDE1adm3GH4MoFSoGh8yHjMmtZ89QdGugkFRZvfOIeIJdY6nPYieWAnVfppvprmw5cxnK08LW9BhQY88wsB+Rbvix8s+kAg4FT4NPvdb/DlQv9YXvcF6ITBPrSSPkoW3vwMjcKOwKyMU+sipK/fm5xzYAV+rHsrK7oYkjIBBlLhIppuh89SiM7gdq6lucRNIVYybQw0X5EtRyY7zEx4XJe2jMTW7oIea2JqeS6XHYcmKyzyaT38PX+/rY2BjhgVFjcoMqiYw==
    username: AgBuPRALuw0FjF1/axe7k7zb0UtqKL8uvBnTw/P3Y9rojNvk1k2fgIwvtHFW07VrVwRkcbahC+A/OY4UEb0/U5HB/oZRYwgUX78Skap5wA2sL7CElTb4FqeBj4Q9KxOzBS+pgfOutOYSckGPRHef1rYAy1ddhiXQU1DSzjO/2WBb+8uiVcPUgVeNKmDQ7zz6BAYpFlnj1LIoldsjD8/GR3jRWpe64hTam57gGWZFa1tDTUbHXO5/DMOpsVxGpoi44RxsXRezFNG4fVSQj+z1ic18JfnaUrPWV6NYmpKnQULK/rvN6mDwDsrtUFVGD09JbL43Q8lCKlIQNy2r9pxZLjIe9Q2qiW8NUDIh3ahfElHeu0Vpqij4b1PSaleO2sg+NGSrk3rmJp9qhnPnl7eS3bJumxhSQuDf1e9pzIfjEvNxr5ZQ+uL3P8C620XS8lNKayvTtcKP7UthVJb2kK/UTskaoASFHLJWadKenPopnzrt4wminLlDgMt3+PxJGGiTypx41hS5M3ruL0LhHjdL8RqPCom7EiIiicGGj2VaoQ2K44vaVjmN7oY1TmOvDRmUGCN/fvutWyYs5MJc0gTm6N4WbcEh0ipPZ6Mql9aVqceqCT433fo17n7WqesVNivQVCnWQD+O4kqI93iuL9DSai6IOIKockGLrUQ4f3kjCKkIFPfE7ggR50u+hqVGrNNvOjQBcPqni4sgNsZfbWo=
  template:
    metadata:
      creationTimestamp: null
      name: transmission
      namespace: pirate
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex
  namespace: pirate
spec:
  encryptedData:
    claim: AgCl7Gf97GQn2AwhnxfCpCDM9CkVs6y8baSlRC1K0hMGKqzXcTxzr26KEiv57orDPfiorLoVbqPiRm6SS6gzHtlH3q3YIvxUiLnTLJKE3/HKymFlVvKIIWNkYBtxMbLqwgUs/YGmLIk8Bsvnrrt4hGEOOrU+ry/ZDw7qB6fH6soKTifEpHYL8N8nTvLVTSf1tdVMYUeMGIAkfHK0A5chYNMi+uCS8hNjKywnxJZ0BTCgqae76CSz7Cj1NIcBrXL3WbpqEAVAEMAIcXKu+ZGjpbgk10S8BxvcdLseoIT30Jf3NDk1sttvH8YvXEeCXpqlDwRGrAhYdaWUKI8U8GdSGBrGXOlyOhtoD9rv+M3SxvrmUFq1lJbQ9EjUpbMFobDse0HaurZwGcq/7kRZLEeGAoEdLfrlkETpkSmGH6o21eQ41+JSTXK7JTINBxPwuMiDPQiX11YHOlWt5Vc6HMfzSOwY8cpCukI5LxDMlbcfMCwXp36gmKlvbPwaK0j4fiQuH41R1u8DddDcynP/6Ay44TXToRObsGaqIvgJ2RS5+Pc9vcq5p0TfgKorcGU7GPtU1NvYJTbIh5+/WAiUR+dBJY13nMZHpXfup2V53nwQsYWjW8Rltlx1+VK3Ra/9pQ8rFCWi+RO3wtLjYcCu28/LkTnGmOsRZJMX4vPbJGD3TyiEjHTndIjblTVWlKUbUzgJMvlLmOtyDpRStXQcNkEUTYAOoUcC7uuK6KQgpw==
  template:
    metadata:
      creationTimestamp: null
      name: plex
      namespace: pirate
