---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: pirate
spec:
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
  selector:
    app: sonarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: pirate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - tvshows.kislan.sk
      secretName: sonarr-tvshows-kislan-sk
  rules:
    - host: tvshows.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: pirate
spec:
  serviceName: sonarr
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.16
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: downloads2
              mountPath: /downloads2
            - name: library
              mountPath: /tv
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Europe/Bratislava
      volumes:
        - name: config
          hostPath:
            path: /var/local/kube-volumes/sonarr3-config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /root/storage/pirate/downloads
            type: DirectoryOrCreate
        - name: downloads2
          hostPath:
            path: /root/storage2/pirate/downloads
            type: DirectoryOrCreate
        - name: library
          hostPath:
            path: /root/storage2/pirate/library/tvshows
            type: DirectoryOrCreate
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
