---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate
  namespace: homepi
spec:
  encryptedData:
    plus_api_key: AgBgmHll+67/0yzl2vjDDqg7Edvcne0DS/BHa0W16DimOdEvhMRoz+a5kNiKheAo1uFLNhxG0nthsrb4vPGNeVGfnEYhLrjIEMymoFP2o9QNnPt/ZaZCuMKhec4mkpGKAbzOoyrU+UIgNWWXYz9/FyDhXomO5vDIWfBZq+LgOWktVfvLXOkcar1nW+Qff9iQs4D6xYHimK0y+m6QbNuawOrvYUG5CkKGGmrHmi3CK215aUwWX8PuQ3E1bil6vpuh/49xTF9bMb8bjTO4GAooZ9AvdHpOSA6iDitlREX3/9V2mVH0++WMf6iU9HZLbhMfSSZZhO4ufQtDFjkY77WMd0VtOrw7InBBcc7/9fUEkU+mRCm3KcbGEAB6RYZU/1AZtBCs63Axxzplt4zrPj71+y70Vmk3ikaJrlI2dt/8qNg9cfOnKNWCD6LiPKK5W0aYdnSEvn98sDWwJVYFzZvKH4VsSUXSVwer6Y3M2q33up5eVVfVNHkf7Cgx+Vfojh2jJa8EEJRaHGFAA+B5p9UORzWc34Kc3mp5JvQwA3hSYat0ztFT8H8Q5Z7gjZgXSaR5pa8K3oO40PRYDpV+HFtSneckrLJSmEGqQV4L07IT1cric5C99nMBJ+at6gwH92pTXMGXIKRWsCVbmD/8DHodwbBqpsJqR9fjXRn2e8Uv9hy4kqkLTaA6SVATJNhoGVM0hm8G9xi/RuI7MoQX4aGNM6OWajHEoTqQuo/ZaLTZS6JyAaRJyoh9d0QFsTDnAdFH5VcpGyNe0qY3nTD7lckAsgZqTJcQkSqoEeHeyR6OUg==
  template:
    metadata:
      creationTimestamp: null
      name: frigate
      namespace: homepi
