apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sensorpi

configMapGenerator:
  - name: livingpi-mqtt-gpio-config
    files:
      - config-map/livingpi/config.yaml

resources:
  - namespace.yaml
  - serviceaccount.yaml

  - secrets.yaml

  - livingpi-mqtt-gpio.yaml
