---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwords
  namespace: sensorpi
spec:
  encryptedData:
    mqtt_password: AgC53EfuU0K6SwXazbwpLzd8dwFAnWUTIDX2glhxQka3aJ4t2gdEe0p74BlZb6stwycAlzN9zzn2wG4Zp6zXA/+qkvVm0PF+1UGc3KEd9+1dfYITv8XAbtJM+gcNhShiK/aSB9joFP4dfKZrpjx0HMZW3cHTTAnL2bqcz3M2X3gg87bmKGOFn3fRhv0oDCy/603rs7A77yDGf1ao/hNsXDZfWH61EsC3ElnWRJwiVMzQ+5oChpxBITWumdxDiYXm6gnRHImUdU3v5PjBiaXFMDTkqNJHXABMUP5x19NLqbyOWzb3aY+FA8Ou8+IC7LcepcGAoBtnH7enCTHXw6k63EXArqDuevT/Xl/VkrJ5PaPoD7975M02wDiQYoEV2pN4NMistpbDKj87YouRKxfXVWbVBbK9uQC2jGtU8sMvvl+2OjvhIZLWhd9Ozsb4vpLikwncs7wwD4U7EW+O+mU8QZECy0h9zXRFCNUcdFsPRLCbI6Xu6EdS2SWrmdUmWQE9yQnmpoDvXNxbsDQuVErQGoXdSIKLulpEbBtj8Dvp2t0gCRm+NpACOwvKxRKbuYeNwzgIcS6WXjjb08CtL05eIeSRHaHxRMI/37tZNr3oWmhZVRjOqfCey/F96SsMQ+Ex6wGvtPkd+7wq4AlaIzYoGOdb2yhTDnlEwtdnHc21qNww0xH3/a96R+4gupFQgY6teJ5kjsZk3eU0mvqIq7o4A5rQkBhVc9JoFv2kbRaD4dV4xrOD8xC/FAqy
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-passwords
      namespace: sensorpi
