mqtt:
  host: ${MQTT_HOSTNAME}
  port: ${MQTT_PORT}
  user: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  topic_prefix: sensorpi/livingpi

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

sensor_modules:
  - name: dht22_sensor
    module: dht22
    type: dht22
    pin: 4

  - name: mhz19
    module: mhz19
    device: "/dev/ttyAMA0"
    range: 5000

sensor_inputs:
  - name: temperature
    module: dht22_sensor
    interval: 10
    digits: 4
    type: temperature

  - name: humidity
    module: dht22_sensor
    interval: 10
    digits: 4
    type: humidity

  - name: co2_mhz19
    module: mhz19
    interval: 10
    ha_discovery:
      device_class: carbon_dioxide

digital_outputs:
  - name: dummy
    module: raspberrypi
    pin: 5
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    publish_initial: true
    retain: yes
