apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garden

configMapGenerator:
  - name: pool-mqtt-gpio-config
    files:
      - config-map/config.yaml

resources:
  - namespace.yaml
  - serviceaccount.yaml

  - secrets.yaml

  - pool-mqtt-gpio.yaml
