#!/usr/bin/with-contenv bash

[[ -n "$EXTRA_PUBLIC_KEY" ]] && \
[[ ! $(grep "$EXTRA_PUBLIC_KEY" /config/.ssh/authorized_keys) ]] && \
echo "$EXTRA_PUBLIC_KEY" >> /config/.ssh/authorized_keys && \
echo "Extra Public key from env variable added"
