#!/usr/bin/with-contenv bash

sed -i '/^\#\?AllowTcpForwarding/c\AllowTcpForwarding yes' /etc/ssh/sshd_config
sed -i '/^\#\?GatewayPorts no/c\GatewayPorts yes' /etc/ssh/sshd_config
sed -i '/^\#\?ClientAliveInterval/c\ClientAliveInterval 60' /etc/ssh/sshd_config
sed -i '/^\#\?ClientAliveCountMax/c\ClientAliveCountMax 10' /etc/ssh/sshd_config
sed -i '/^\#\?TCPKeepAlive/c\TCPKeepAlive yes' /etc/ssh/sshd_config
sed -i '/^\#\?MaxSessions/c\MaxSessions 100' /etc/ssh/sshd_config
