---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kube-state-metrics
      version: "5.30.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-system
      interval: 5m
  releaseName: kube-state-metrics
  values:
    serviceAccount:
      name: kube-state-metrics

    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
