---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: kube-system
      interval: 5m
  releaseName: pihole
  values:
    replicaCount: 2
    serviceDns:
      enabled: true
      type: LoadBalancer
    # dnsHostPort:
    #   enabled: true
    adlists:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
