apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tunnel

configMapGenerator:
  - name: ssh-tunnel-config
    files:
      - config-map/script
      - config-map/extra-ssh-key-script

resources:
  - namespace.yaml
  - serviceaccount.yaml

  - secrets.yaml

  - marek-rpi-hass.yaml
  # - remote-dev.yaml
