apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tunnel

resources:
  - namespace.yaml
  - serviceaccount.yaml

  - ssh-tunnel-config.yaml
  - secrets.yaml

  - marek-rpi-hass.yaml
