---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ssh-tunnel-cfg
  namespace: tunnel
data:
  script: |
    #!/usr/bin/with-contenv bash

    sed -i '/^\#\?AllowTcpForwarding/c\AllowTcpForwarding yes' /etc/ssh/sshd_config
    sed -i '/^\#\?GatewayPorts no/c\GatewayPorts yes' /etc/ssh/sshd_config
    sed -i '/^\#\?ClientAliveInterval/c\ClientAliveInterval 60' /etc/ssh/sshd_config
    sed -i '/^\#\?ClientAliveCountMax/c\ClientAliveInterval 5' /etc/ssh/sshd_config

  extra-ssh-key-script: |
    #!/usr/bin/with-contenv bash

    [[ -n "$EXTRA_PUBLIC_KEY" ]] && \
    [[ ! $(grep "$EXTRA_PUBLIC_KEY" /config/.ssh/authorized_keys) ]] && \
    echo "$EXTRA_PUBLIC_KEY" >> /config/.ssh/authorized_keys && \
    echo "Extra Public key from env variable added"
