---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: botkube
      version: "v1.14.0"
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: kube-system
      interval: 5m
  releaseName: botkube
  values:
    settings:
      clusterName: "homelab"
    communications:
      default-group:
        socketSlack:
          enabled: "true"
          channels:
            default:
              name: "kube-homelab"
    extraEnv:
      - name: "BOTKUBE_COMMUNICATIONS_DEFAULT-GROUP_SOCKET__SLACK_BOT__TOKEN"
        valueFrom:
          secretKeyRef:
            name: slack
            key: bot-token
      - name: "BOTKUBE_COMMUNICATIONS_DEFAULT-GROUP_SOCKET__SLACK_APP__TOKEN"
        valueFrom:
          secretKeyRef:
            name: slack
            key: app-token
