---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: botkube
spec:
  encryptedData:
    app-token: AgA0a5PQEEAT/sCy1Zh0D6E5ga3rjpkfSfBV/6G3EyQ++yp66p1PMfAbTgzlXGweG/LKtVNJQ2iln1akwNkOOYsJiyDyJOtV2+KpDmh5Ds18kU1dmipUYq5xZLMWbnc0c4lXPPpck/zv90UwwmlCwxdXrs+5UC2POdzWVxFCzW+SBWc2Ba1A6/qRWsq5vcVkwjm+M5WJLwpcI5KuHwSDgHofrWQ1UpksYwDnMV4KA7tb1zlKsFYsJktd0DFW6E5DJdbMICu4b2nQvShHM3Yg2dDoVvKXqPDNTXhzq5TL4CAv+k8DiLRwh+WlXWSwDQ7MHBbTH1ruTWK5WcmCJPWlrDR/Z5ZsCsWIl8ytnLGtX4vU80QyZCGMrdmZbxqQNeuObIqWLjJ6HhTBvupIsATYWeD+xqp1td8YrAQBJqHdGFQor98iEodGa0CdoSOU0Y3kHBB289F/0f297MuukG3MtbqF6dbv6+kq3X6WXorDLWfgX3e/Ld/X/uNIqazHlGi4dIMiSuW1C4LpvCzUmFdcWIvOGet76WW/VpTtcDsEjvUgrvBBKCpEsSyQ7GUQT1tMtd1gZVBRvqtAs3HHQtOs5VWLf33nHpf+g6bo0p9Bd6LXb8vFsrGPJSyIjPwlDyamf2e2Hw76NDrdkjekIwuUxtHOA6vtSqtWWw6EIMlw74497ymVMMjNXpn9oE/ZyBve/zxe/AiTsT9fmB2jQVQgut/rVS03JuB4bMVCi5qfBnBzxnLjZQ5bCRVfu0/96sBqWpWqSb/ldotudGo+pzuDjwbg7WgZ4ElxhugapChjmS+ZTMQbMx5ytnVWnVoI3JwzZ8Bz
    bot-token: AgCGGBBx6hsYpuBzjm7i04iPORmXChmVyETvGfnzs/ZUWC6QQT81d/7R3LvGlpfAt65O01+NYd+JbGIGNlMhjTq6/d2pwIT5w6ct5fUl7TwYsMGD2LLZlT7GurM5Gr1l2cMz/Iy6ke5L7L6KEGXOZYqCPDCgR1iO48DiQy2rIGfm/UL7oeEl0ULy9gK3W8YKZRT5wRKotNJGLrT/ZFgu/IIMp2lq1O6NRQQr4zF60PyCobjhGU8nU2HbEadA67twNEnYLT+9G+J+oSTb4EZElKfRPDPRuWZPwE/jy8WJ59te0a+q2rQ5DJWD2V1cDcMLCz8I5WwL7Cw1KkSQOYTeRDIkfZzxrFwL44z7KYUL2fRzup9vhPei0dtbTl4PJxBzf0ysmIlgq0e0Kl9KacW7/E82ayJCUr80QK0yWW6np7zieMoY2zrRBDJ+DW6RsYvxMV4irETpIZDAUh8+w6DQJLo2h+DSpd2FFrcKcZlQ/c9+MIX+4xyN+OMOTiFabIkG6hZbBO2vMLKXCxNmDmp6rGDt+HKVlvwhLpvZjnCkqaLBzvEFsNQIkeimtc2fEqqEh/SHIj5D/T+m7RddhXeXc+Wxbz9tkT7E3xOIkl/iAaqDC8ni6T8FhEMJ5NGJ6nekrNteAykwRNdNDvy/yu11sGg8sMakEdROxlc5DRiT5mKAtBXD3sMcKolpxagiI0HzdWLoO5jnwzeABCEfHDA2kgAUiCeeRVjoCLbXjO3bPYwwvg1OG7LbTmVtsfosQ051FXGYcVGPIqutqA==
  template:
    metadata:
      creationTimestamp: null
      name: slack
      namespace: botkube
