---
apiVersion: v1
kind: Service
metadata:
  name: wedding-external
  namespace: wedding
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wedding-external
  namespace: wedding
subsets:
  - addresses:
      - ip: 165.227.250.207
    ports:
      - port: 80
        protocol: TCP
        name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wedding
  namespace: wedding
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - hajdukova.kislan.sk
      secretName: hajdukova-kislan-sk
  rules:
    - host: hajdukova.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wedding-external
                port:
                  number: 80
