---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: "4.47.3"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-system
      interval: 5m
  releaseName: prometheus-node-exporter
  values:
    serviceAccount:
      name: node-exporter

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 180Mi
