---
apiVersion: v1
kind: Service
metadata:
  name: kodiconnect-app
  namespace: kodi-connect
spec:
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
  selector:
    app: kodiconnect-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kodiconnect
  namespace: kodi-connect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
        - kodiconnect.kislan.sk
      secretName: kodiconnect-kislan-sk
  rules:
    - host: kodiconnect.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kodiconnect-app
                port:
                  number: 3005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodiconnect-app
  namespace: kodi-connect
  annotations:
    fluxcd.io/automated: "false"
spec:
  selector:
    matchLabels:
      app: kodiconnect-app
  replicas: 1
  template:
    metadata:
      labels:
        app: kodiconnect-app
    spec:
      serviceAccountName: kodi-connect
      containers:
        - name: kodiconnect-app
          image: kodiconnect/kodi-connect:master
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: admin_password
            - name: MONGO_URL
              value: mongodb://mongo:27017/kodi
            - name: HOST_URL
              value: https://kodiconnect.kislan.sk
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session
                  key: secret
            - name: BUGSNAG_KEY
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: api_key
            - name: EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: email
                  key: address
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email
                  key: password
            - name: LWA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lwa
                  key: id
            - name: LWA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lwa
                  key: secret
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: secret
          resources:
            requests: {}
            limits:
              cpu: 300m
              memory: 200Mi
