---
apiVersion: v1
kind: Service
metadata:
  name: hass
  namespace: homepi
spec:
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
  selector:
    app: hass
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
  namespace: homepi
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - hass.kislan.sk
      secretName: hass-kislan-sk
  rules:
    - host: hass.kislan.sk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hass
                port:
                  number: 8123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hass
  namespace: homepi
  annotations:
    fluxcd.io/automated: "false"
spec:
  serviceName: hass
  replicas: 1
  selector:
    matchLabels:
      app: hass
  template:
    metadata:
      labels:
        app: hass
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - name: config
          hostPath:
            path: /var/local/kube-volumes/hass-config
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /data/hass-data
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: hass
          image: ghcr.io/home-assistant/home-assistant:2025.8.3
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: DATABASE_URL
              value: postgresql://hass:$(PG_PASSWORD)@postgres12.homepi.svc.cluster.local:5432/hass
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
