---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: homepi
spec:
  ports:
    - name: ws
      port: 5580
      targetPort: 5580
      protocol: TCP
  selector:
    app: matter-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matter-server
  namespace: homepi
spec:
  serviceName: matter-server
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      # Required for mDNS to work correctly
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - name: data
          hostPath:
            path: /var/local/kube-volumes/matter-server-data
            type: DirectoryOrCreate
        # Required for Bluetooth via D-Bus
        - name: dbus
          hostPath:
            path: /run/dbus
            type: Directory
      containers:
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:stable
          ports:
            - containerPort: 5580
              name: ws
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
