---
apiVersion: v1
kind: Service
metadata:
  name: zigbee
  namespace: homepi
spec:
  ports:
    - name: http
      port: 18080
      targetPort: 18080
  selector:
    name: zigbee
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee
  namespace: homepi
spec:
  serviceName: zigbee
  replicas: 1
  selector:
    matchLabels:
      name: zigbee
  template:
    metadata:
      labels:
        name: zigbee
    spec:
      volumes:
        - name: sonoff
          hostPath:
            path: /dev/ttyUSB1
            type: CharDevice
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: data
          hostPath:
            path: /var/local/kube-volumes/zigbee-data
            type: DirectoryOrCreate
      containers:
        - name: zigbee
          image: koenkk/zigbee2mqtt:2.0.0
          ports:
            - containerPort: 18080
              name: http
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Bratislava
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: udev
              mountPath: /run/udev
            - name: sonoff
              mountPath: /dev/ttyUSB1
            - name: data
              mountPath: /app/data
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
