---
apiVersion: v1
kind: Service
metadata:
  name: zwave
  namespace: homepi
spec:
  ports:
    - name: http
      port: 8091
      targetPort: 8091
    - name: ws
      port: 3000
      targetPort: 3000
  selector:
    name: zwave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zwave
  namespace: homepi
spec:
  serviceName: zwave
  replicas: 1
  selector:
    matchLabels:
      name: zwave
  template:
    metadata:
      labels:
        name: zwave
    spec:
      containers:
        - name: zwave
          image: zwavejs/zwave-js-ui:11.3.0
          livenessProbe:
            failureThreshold: 12
            httpGet:
              httpHeaders:
                - name: Accept
                  value: text/plain
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
            - containerPort: 3000
              name: ws
              protocol: TCP
          # env:
          #   - name: NETWORK_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: zwavejs
          #         key: network_key
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: zstick
              mountPath: /dev/ttyUSB0
            - name: data
              mountPath: /usr/src/app/store
      volumes:
        # - name: config <-- if putting your settings.json in a secret
        #   secret:
        #     defaultMode: 420
        #     secretName: zwavejs2mqtt
        - name: zstick
          hostPath:
            path: /dev/ttyUSB0
            type: CharDevice
        - name: data
          hostPath:
            path: /var/local/kube-volumes/zwavejs-data
            type: DirectoryOrCreate
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: edge
          operator: Equal
          value: homenuc
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edge
                    operator: In
                    values:
                      - homenuc
