name: Kustomize Build

on: [push]

jobs:
  kustomize_build:
    name: Kustomize Build
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - uses: actions/checkout@v4

      - name: Install Kubectl
        run: ./scripts/install_kubectl.sh

      - name: Install Flux
        run: ./scripts/install_flux.sh

      - name: Instal Flux k8s
        run: flux install

      - name: Kustomize Build Secrets
        run: kubectl kustomize secrets/ | kubectl apply -f -

      - name: Kustomize Build Infra
        run: kubectl kustomize infra/ | kubectl apply -f -

      - name: Kustomize Build Apps
        run: kubectl kustomize apps/ | kubectl apply -f -
