name: Build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kustomize_build:
    name: Kustomize Build
    runs-on: ubuntu-latest
    steps:
      # - name: Create k8s Kind Cluster
      #   uses: helm/kind-action@v1
      - name: Create k3s Cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: "v1.31.4+k3s1"

      - uses: actions/checkout@v5

      - name: Install Kubectl
        run: ./scripts/install_kubectl.sh

      - name: Install Flux
        run: ./scripts/install_flux.sh

      - name: Instal Flux k8s
        run: flux install

      - name: Kustomize Build Secrets
        run: kubectl kustomize secrets/ | kubectl apply -f -

      - name: Kustomize Build Infra
        run: kubectl kustomize infra/ | kubectl apply -f -

      - name: Wait for Cert Manager Helm Release to reconcile
        run: flux reconcile helmrelease -n cert-manager cert-manager

      - name: Kustomize Build Apps
        run: kubectl kustomize apps/ | kubectl apply -f -
  
  devcontainer_build:
    name: Devcontainer Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          package-manager-cache: false

      - name: Install Devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build Devcontainer
        run: devcontainer up --workspace-folder .
